#!/usr/bin/env bash
# Run this from the root directory

# Soure the approvals script
source "approvals.bash"

# Test commands
cd ./test || exit
context "standard operation"
  describe "sample cli test"
    approve "./sample-cli-app.sh"
    approve "./sample-cli-app.sh --help"
    approve "./sample-cli-app.sh say"
    approve "./sample-cli-app.sh say hello"
    approve "./sample-cli-app.sh say hello" "alternative_fixture_file"

context "when APPROVALS_DIR is set"
  APPROVALS_DIR=alt-approvals

  describe "writes approvals to a different directory"
    approve "./sample-cli-app.sh"

context "when APPROVALS_PREFIX is set"
  APPROVALS_PREFIX="_prefix"

  describe "writes approval files with the given prefix"
    approve "./sample-cli-app.sh"

  context "and a context prefix is provided" "_context_prefix"
    describe "it overrides the global prefix"
      approve "./sample-cli-app.sh"
